### ISSUE TITLE
Folderstats works in terminal but not in pycharm

### ISSUE THREAD

**Issue by datatalking** [njanakiev/folderstats#18] opened 2022-07-27 23:31 UTC
I've installed in in pip, anaconda and restarted my pycharm but it refuses to even recognize folderstats as an installed package.

If I run folderstats 'path/filename' it works.

Does folderstats not get installed on path for a reason via pip or is there a magic method for install?

<img width="726" alt="Screen Shot 2022-07-27 at 4 29 38 PM" src="https://user-images.githubusercontent.com/11813209/181389822-490ec17f-981d-48b3-911e-070833f9ab15.png">

<img width="624" alt="Screen Shot 2022-07-27 at 4 29 15 PM" src="https://user-images.githubusercontent.com/11813209/181389695-c7ebe3cb-cc20-499d-ad9c-f3162ea57ce7.png">

**Comment by njanakiev** [comment] 2024-05-15 14:51
Thank you for the issue! I'm sadly unable to reproduce this issue on VSCode. Feel free to look into it and file a PR if you manage to find a solution. Closing it for now.

**Closed by njanakiev** 2024-05-15 14:51 UTC
